# Generated by Django 4.2.16 on 2024-10-27 15:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('img_link', models.URLField(max_length=999)),
                ('category', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('product_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
            ],
        ),
    ]
